src/alexer.mll
test/fast/language/WFTRUE_test.tla

This change ensures that `TRUE` and `FALSE`
can be used as fairness subscripts, for
example `WF_TRUE(TRUE)`.
Previously, the string `WF_TRUE` was lexed
as punctutation `WF_` followed by an
identifier `TRUE`, instead of the keyword `TRUE`.
This commit adds also a test module for this case.

BUG: lex keywords in WF_, SF_ subscripts

---

src/tlapm.ml
test/fast/fingerprint/load_v8old_test.tla.disabled

This change makes `.tlacache` the default auxiliary directory, following #16.
In the future, a command-line option could be added for specifying the auxiliary directory.

API: change default aux dir to `.tlacache`

---

src/expr/e_elab.ml
test/fast/language/DuplicateEXCEPT.tla
test/fast/language/EXCEPTMultipleBrackets_test.tla

These changes ensure that `@` and multiple assignments in an `EXCEPT` are correctly interpreted.

correctly interpret multiple `EXCEPT` assignments

---

src/backend/fingerprints.ml
src/expr/e_elab.ml
src/module/m_dep.ml
src/module/m_elab.ml
src/module/m_fmt.ml
src/tlapm.ml
test/TOOLS/do_one_test
test/fast/enabled_cdot/ENABLED_INSTANCE_nullary_op_test.tla
test/fast/enabled_cdot/ENABLED_INSTANCE_nullary_op_two_vars_test.tla
test/fast/enabled_cdot/ENABLED_INSTANCE_op_with_args_test.tla
test/fast/enabled_cdot/Level_of_parametric_INSTANCE_test.tla
test/fast/language/EXTENDS_in_submodule_test.tla
test/fast/language/INSTANCE_inside_LET_fingerprint_test.tla
test/fast/language/INSTANCE_inside_LET_test.tla
test/fast/language/INSTANCE_shift_due_to_omitted_modunits_test.tla

These changes include bug fixes:
- cdf6240de4ddd2466a995886950c260477ecf3a7: recomputing the levels of operators after instantiation, because parametric `INSTANCE` changes the arity of operators, and also can change the level of declared identifiers. A change in arity makes the level information of operators outdated, and requires recomputing the operator's level information.
- e27d639689a211d47e3986470c570497b12eb665: bind primed occurrences of variables before instantiation, when these appear in scope of `ENABLED` inside the definition of an operator that takes arguments. This change:
- ensures correct binding of primed occurrences of variables when instantiating, for example, the operator `A(z) == ENABLED (x' # y')` (as in the added test module)
- raises an error during operator …

`INSTANCE` within `LET`, `ENABLED` in parametrized `INSTANCE`, `ENABLED` in instantiated operators with parameters, and related changes

---

translate/dune

`ptl_to_trp` is installed in `.../bin` but `tlapm` expects to find it in `.../lib/tlapm/backends/bin`.

fix install location for ptl_to_trp

---

test/fast/regression/setEuclid_test.tla

I investigated in more detail the issue with the failed regression test. The failing obligation was
```Cardinality (S) = 1 => S = {CHOOSE t \in S : TRUE}```
During pre-processing, the old SMT backend simplified the right-hand side of this implication to
```\A x : x \in S <=> (S # {} => x \in S)```
which, together with the hypothesis ```S # {}``` available from the context, made the proof trivial.
In fact, the same step was proved even without appealing to CardThm, and without the assumption
of the left-hand side of the implication. This is clearly unsound.
This small PR contains a fixed proof of this test case.
NB: Running tlapm with the option `--debug tempfiles` still produces the input files for Isabelle
and Zenon, but no longer for SMT. More precisely, the files are created but are …

fixed bogus proof in setEuclid_test.tla

---

src/type/t_hyps.ml

In order to get the desired lazy behavior, you simply need to add a `lazy` annotation on the right-hand-side argument of `||>` and `&&>` so they can do shortcut evaluation.

fix laziness in t_hyps.ml

---

deps/isabelle/Makefile

HTTP endpoints used to download the Isabelle/HOL during the build no longer work.

Use HTTPS to download the Isabelle.

---

src/expr/e_anon.ml
src/expr/e_elab.ml
src/expr/e_elab.mli

A rather subtle bug caused by the use of nested visitors.
fixes #77

fix wrong expansion of @ in nested EXCEPT

---

.vscode/launch.json
Makefile
src/dune

This will generate a `tlapm.bc` OCaml bytecode file in `_build/default/src` which can be loaded by `ocamldebug`. Dune 2.0+ requires this to be explicitly specified ([docs](https://dune.readthedocs.io/en/stable/reference/dune/executable.html)):
>Given an executable stanza with (name \<name\>), Dune will know how to build \<name\>.exe. If requested, it will also know how to build \<name\>.bc and \<name\>.bc.js (Dune 2.0 and up also need specific configuration (see the modes optional field below)).
`ocamldebug` also requires everything to be built with the `-g` flag, which is the case by default with Dune; see output of `dune printenv .`.
Ref https://github.com/tlaplus/tlapm/discussions/143
I also added a debug launch profile for VS Code, and added the …

Emit bytecode in dune build for debugging

---

deps/isabelle/.gitignore
deps/isabelle/Makefile
deps/isabelle/dune
deps/isabelle/dune.mk
dune-project
isabelle/CaseExpressions.thy
isabelle/Constant.thy
isabelle/FixedPoints.thy
isabelle/Functions.thy
isabelle/IntegerArithmetic.thy
isabelle/IntegerDivision.thy
isabelle/Integers.thy
isabelle/Makefile
isabelle/PredicateLogic.thy
isabelle/ROOT
isabelle/SetTheory.thy
isabelle/Strings.thy
isabelle/Tuples.thy
isabelle/Zenon.thy
isabelle/dune
isabelle/dune.mk
isabelle/examples/Allocator.thy
isabelle/examples/AtomicBakeryG.thy
isabelle/tests/Tests.thy
test/TOOLS/do_one_test
test/dune
tlapm.opam

This PR tries to address https://github.com/tlaplus/tlapm/issues/133.
The idea is to rewrite `Nat` as a value instead of its use in expressions like `n ∈ Nat`. So expressions like `[P -> Nat]` are also rewritten. E.g. the following lemma was failing before this change (while the same with `a` instead of `Nat` was passing):
```
lemma
fixes p :: "c" and f and i
assumes "f ∈ [p → Nat]" and "i ∈ p"
shows "f[i] ∈ Nat"
using assms by auto
```
All the tests are still passing (tests, community modules, examples repo).
The `isabelle/examples/AtomicBakeryG.thy` example still fails, but now the first error is at line `535` instead of `325`.

Rewrite Nat to {x ∈ Int : 0 ≤ x} instead of n ∈ Nat to (n ∈ Int ∧ 0 ≤ n).

---

dune-project
tlapm.opam

Without this field, newer versions of `opam` will print out the following warning when running `make opam-deps`:
>[WARNING] Failed checks on tlapm package definition from source at
git+file:///mnt/data/ahelwer/src/tlaplus/proofs#main:
warning 68: Missing field 'license'
This tiny change fixes that warning by adding the [SPDX short form](https://spdx.org/licenses/BSD-2-Clause.html) of the repo's license to the `tlapm.opam` file.

Add license field to opam package definition file

---

INSTALL.md

I encountered the following errors after pulling the latest commits from main. I manually installed `eio_main` with `opam install eio_main` and `lsp` with `opam install lsp` before noticing `make opam-deps-opt`:
```shell
-> % make
dune build
File "lsp/bin/dune", line 7, characters 26-34:
7 |  (libraries tlapm_lsp_lib eio_main cmdliner))
^^^^^^^^
Error: Library "eio_main" not found.
-> required by _build/default/lsp/bin/tlapm_lsp.exe
-> required by alias lsp/bin/all
-> required by alias default
make: *** [build] Error 1
```
```shell
dune build
File "lsp/bin/dune", line 7, characters 12-25:
7 |  (libraries tlapm_lsp_lib eio_main cmdliner))
^^^^^^^^^^^^^
Error: Library "tlapm_lsp_lib" in _build/default/lsp/lib is hidden (optional
with unavailable dependencies).
-> required by …
```

Add `make opam-deps-opt` to INSTALL.md

---

lsp/lib/parser/parser.ml
src/tlapm_lib.ml
src/tlapm_lib.mli

This adds a simple string -> parse tree method in TLAPM's public API, so it can be hit by non-inline unit tests.

Exposed parse method in TLAPM API

---

.github/workflows/ci.yml

@kape1395 is there a reason we run the CI on both macOS 13 and 14? Version 13 machines are very slow, taking about twice as long to complete as the rest. This PR just changes it to use macos-latest.

CI: Use macos-latest instead of versions 13 & 14

---

.github/workflows/ci.yml

- BUG: correct quoting of environment-variable values in the script `setup_shell_env.py`, to avoid errors in CI workflow of `release.yml`.
- run workflow of file `.github/workflows/release.yml` whenever the file changes, and also twice a year.
- add underscores and "UTC" to tag name created by GitHub Actions when running `release.yml`.

CI: show logs for each test file

---

src/backend/fpfile.ml

Change the magic number for fingerprint files, because the file format has changed.

change magic number for fingerprint files

---

examples/SimpleEventually.tla

Two actions, `A` and `B`, allow for the discussion of the non-distributiveness of (weak) fairness.
Happy to remove `Equiv` again.

Make SimpleEventually proof a bit less simple.

---

src/module/m_visit.ml
test/bugs/instance_mutate.tla
test/bugs/instance_mutate_test.tla

It was failing before with `tlapm ending abnormally with Failure("unknown bound variable")`.
This fixes a case mentioned in https://github.com/tlaplus/tlapm/issues/151#issuecomment-2365142957

Fix instantiation of a module containing USE.

---

src/encode/n_axioms.ml

The bug originated from axiom "TupExcept" which specifies the replacement of a element in a tuple using EXCEPT.  For instance, the axiom could be used to generate the equality `[ <<a, b, c>> EXCEPT ![2] = d ] = <<a, d, c>>`.
The index of the element to change was not set correctly.  Also, the axiom is only put in the result if both a tuple and the EXCEPT operator appear in the obligation, making this bug harder to detect.
This closes #201

Fixed SMT soundness bug involving tuples and EXCEPT

---

src/expr.mli
src/expr/e_anon.ml
src/expr/e_levels.ml
src/expr/e_levels.mli
src/expr/e_tla_norm.ml
src/util/deque.ml
src/util/deque.mli

Follow-up to https://github.com/tlaplus/tlapm/pull/148#issuecomment-2595420647
Should make #186 unnecessary.
cc @kape1395

Memoize level computation to avoid exponential behavior

---

lsp/lib/analysis/step_renumber.ml
lsp/lib/analysis/step_renumber.mli
lsp/lib/docs/docs.ml
lsp/lib/docs/docs.mli
lsp/lib/server/handlers.ml

No changes are required to the main tlapm codebase.

LSP: Support for proof step re-numbering.

---

deps/ls4/ls4.patch

My C++ compiler (latest MacOS) complains about having an identifier right after a string literal, without a space inbetween. Apparently this corresponds to a new syntax introduced in C++11.
The fix is to add a space, and it should be completely compatible with other C++ compilers.
The problem occurs in the LS4 source code, so the fix is in the patch we apply to LS4 before compiling.

fix for C++11 string literal syntax change

---

src/encode/n_axioms.ml

The corrected axiom lets you deduce `SubSeq(s, m, n) \in Seq(S)` when `n < m`. This is correct as the expression denotes the empty sequence in that case.

Fix SubSeqTyping axiom for the empty case

---

.github/workflows/ci.yml

In support of #217. All proofs are currently skipped, but can be checked by deleting their `-and -not -name "SpecName_proofs.tla"` line. This supports PRs which try to make TLAPM check these proofs.

CI: check library proofs

---

library/SequencesExtTheorems_proofs.tla

This makes the library proofs passing on my PC.
Strangely, `<2>2` needed to be separated from `<2>1` to pass.

Decompose proofs so that they pass on my PC.

---

.ocamlformat
lsp/lib/docs/proof_step.ml
src/backend/fingerprints.ml

The fingerprint calculation reverted to is_const (as it is now done in the main branch) instead of get_level to make the fingerprint calculation independent of the level assignment. This is done to avoid having level assignments on the critical path in the LSP, as it is too slow. In my case, it took 30 seconds to calculate the levels, which blocks subsequent LSP commands.

Make the LSP independent of level assignment.

---

lsp/lib/docs/proof_step.ml
src/backend.mli
src/backend/fingerprints.ml
src/backend/fingerprints.mli

Added an option to ignore the level information while calculating a fingerprint.
By default, it is false; thus, the existing behaviour is retained.
The fingerprints with levels ignored are only used as hash functions to transfer proof state between the document versions in the LSP.
This time, the tests are passing.

Make LSP independent of level calculations (2nd attempt).
